# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window3_choosetable.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choosetable_window(object):
    def setupUi(self, choosetable_window):
        choosetable_window.setObjectName("choosetable_window")
        choosetable_window.resize(650, 650)
        choosetable_window.setMinimumSize(QtCore.QSize(650, 650))
        choosetable_window.setMaximumSize(QtCore.QSize(650, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        choosetable_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(choosetable_window)
        self.centralwidget.setObjectName("centralwidget")
        self.background_fillter = QtWidgets.QLabel(self.centralwidget)
        self.background_fillter.setGeometry(QtCore.QRect(0, 0, 650, 650))
        self.background_fillter.setMinimumSize(QtCore.QSize(650, 650))
        self.background_fillter.setMaximumSize(QtCore.QSize(650, 650))
        self.background_fillter.setMouseTracking(False)
        self.background_fillter.setTabletTracking(False)
        self.background_fillter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.background_fillter.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.background_fillter.setAutoFillBackground(False)
        self.background_fillter.setStyleSheet("QLabel{\n"
"    background: rgba(34,65,134,60%);\n"
"}")
        self.background_fillter.setText("")
        self.background_fillter.setObjectName("background_fillter")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 650, 650))
        self.background.setMinimumSize(QtCore.QSize(650, 650))
        self.background.setMaximumSize(QtCore.QSize(650, 650))
        self.background.setMouseTracking(False)
        self.background.setTabletTracking(False)
        self.background.setFocusPolicy(QtCore.Qt.NoFocus)
        self.background.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.background.setAutoFillBackground(False)
        self.background.setStyleSheet("")
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("img/background.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.logout = QtWidgets.QPushButton(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(260, 540, 131, 41))
        self.logout.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(74,167,72,95%);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 14pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid #4AA748;\n"
"    background-color: rgba(132,193,65,65%);\n"
"    font-weight: bold;\n"
"}")
        self.logout.setAutoRepeatDelay(300)
        self.logout.setObjectName("logout")
        self.data_table = QtWidgets.QPushButton(self.centralwidget)
        self.data_table.setGeometry(QtCore.QRect(180, 220, 291, 91))
        self.data_table.setStyleSheet("QPushButton{\n"
"    font: 75 16pt \"HungHau\";\n"
"    border-radius: 20px;\n"
"    background-color: rgba(34,65,134,90%);\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 18pt \"HungHau\";\n"
"    border-radius: 20px;\n"
"    border: 7px solid rgb(59,108,212);\n"
"    background-color: rgba(59,108,212,65%);\n"
"    font-weight: bold;\n"
"}")
        self.data_table.setAutoRepeatDelay(300)
        self.data_table.setObjectName("data_table")
        self.infouser_table = QtWidgets.QPushButton(self.centralwidget)
        self.infouser_table.setGeometry(QtCore.QRect(180, 320, 291, 91))
        self.infouser_table.setStyleSheet("QPushButton{\n"
"    font: 75 16pt \"HungHau\";\n"
"    border-radius: 20px;\n"
"    background-color: rgba(34,65,134,90%);\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 18pt \"HungHau\";\n"
"    border-radius: 20px;\n"
"    border: 7px solid rgb(59,108,212);\n"
"    background-color: rgba(59,108,212,65%);\n"
"    font-weight: bold;\n"
"}")
        self.infouser_table.setAutoRepeatDelay(300)
        self.infouser_table.setObjectName("infouser_table")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(50, 40, 150, 150))
        self.logo.setMinimumSize(QtCore.QSize(150, 150))
        self.logo.setMaximumSize(QtCore.QSize(175, 175))
        self.logo.setStyleSheet("QLabel{\n"
"    image: url(:/newPrefix/logo.png);\n"
"}\n"
"QLabel:hover{\n"
"    image: url(:/newPrefix/logo HHE.png);\n"
"}")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("img/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setWordWrap(False)
        self.logo.setOpenExternalLinks(False)
        self.logo.setObjectName("logo")
        self.signup_admin = QtWidgets.QPushButton(self.centralwidget)
        self.signup_admin.setGeometry(QtCore.QRect(180, 420, 291, 91))
        self.signup_admin.setStyleSheet("QPushButton{\n"
"    font: 75 16pt \"HungHau\";\n"
"    border-radius: 20px;\n"
"    background-color: rgba(34,65,134,90%);\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 18pt \"HungHau\";\n"
"    border-radius: 20px;\n"
"    border: 7px solid rgb(59,108,212);\n"
"    background-color: rgba(59,108,212,65%);\n"
"    font-weight: bold;\n"
"}")
        self.signup_admin.setAutoRepeatDelay(300)
        self.signup_admin.setObjectName("signup_admin")
        self.password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(230, 90, 351, 41))
        self.password_input.setStyleSheet("QLineEdit{\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.password_input.setText("")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setCursorPosition(0)
        self.password_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.password_input.setObjectName("password_input")
        self.account_input = QtWidgets.QLineEdit(self.centralwidget)
        self.account_input.setGeometry(QtCore.QRect(230, 40, 351, 41))
        self.account_input.setStyleSheet("QLineEdit{\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.account_input.setText("")
        self.account_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.account_input.setCursorPosition(0)
        self.account_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.account_input.setObjectName("account_input")
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setGeometry(QtCore.QRect(390, 140, 191, 41))
        self.update_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(74,167,72,95%);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 14pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid #4AA748;\n"
"    background-color: rgba(132,193,65,65%);\n"
"    font-weight: bold;\n"
"}")
        self.update_button.setAutoRepeatDelay(300)
        self.update_button.setObjectName("update_button")
        self.background.raise_()
        self.background_fillter.raise_()
        self.logout.raise_()
        self.data_table.raise_()
        self.infouser_table.raise_()
        self.logo.raise_()
        self.signup_admin.raise_()
        self.password_input.raise_()
        self.account_input.raise_()
        self.update_button.raise_()
        choosetable_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(choosetable_window)
        QtCore.QMetaObject.connectSlotsByName(choosetable_window)

    def retranslateUi(self, choosetable_window):
        _translate = QtCore.QCoreApplication.translate
        choosetable_window.setWindowTitle(_translate("choosetable_window", "PHẦN MỀM TƯ VẤN TUYỂN SINH TRƯỜNG ĐẠI HỌC VĂN HIẾN"))
        self.logout.setText(_translate("choosetable_window", "Đăng Xuất"))
        self.data_table.setText(_translate("choosetable_window", "Dữ liệu tư vấn tuyển sinh"))
        self.infouser_table.setText(_translate("choosetable_window", "Dữ liệu câu hỏi thí sinh"))
        self.signup_admin.setText(_translate("choosetable_window", "Tạo tài khoản admin"))
        self.password_input.setPlaceholderText(_translate("choosetable_window", "   Mật khẩu"))
        self.account_input.setPlaceholderText(_translate("choosetable_window", "   Tài khoản"))
        self.update_button.setText(_translate("choosetable_window", "Cập nhật mật khẩu"))
