# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window5_infouser.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_userinfo_window(object):
    def setupUi(self, userinfo_window):
        userinfo_window.setObjectName("userinfo_window")
        userinfo_window.resize(1100, 650)
        userinfo_window.setMinimumSize(QtCore.QSize(1100, 650))
        userinfo_window.setMaximumSize(QtCore.QSize(1100, 650))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        userinfo_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(userinfo_window)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(40, 10, 100, 100))
        self.logo.setMinimumSize(QtCore.QSize(100, 100))
        self.logo.setMaximumSize(QtCore.QSize(100, 100))
        self.logo.setStyleSheet("")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("img/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setWordWrap(False)
        self.logo.setOpenExternalLinks(False)
        self.logo.setObjectName("logo")
        self.tittle_window = QtWidgets.QPushButton(self.centralwidget)
        self.tittle_window.setGeometry(QtCore.QRect(290, 10, 511, 101))
        font = QtGui.QFont()
        font.setFamily("HungHau")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tittle_window.setFont(font)
        self.tittle_window.setTabletTracking(False)
        self.tittle_window.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 16pt \"HungHau\";\n"
"    border-radius: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 20pt \"HungHau\";\n"
"    border-radius: 20px;\n"
"    font-weight: bold;\n"
"}")
        self.tittle_window.setObjectName("tittle_window")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(40, 580, 91, 41))
        self.back_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(74,167,72,95%);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 14pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid #4AA748;\n"
"    background-color: rgba(132,193,65,65%);\n"
"    font-weight: bold;\n"
"}")
        self.back_button.setAutoRepeatDelay(300)
        self.back_button.setObjectName("back_button")
        self.deleteall_button = QtWidgets.QPushButton(self.centralwidget)
        self.deleteall_button.setGeometry(QtCore.QRect(940, 580, 121, 41))
        self.deleteall_button.setStyleSheet("QPushButton{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(34,65,134,90%);\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 14pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(59,108,212);\n"
"    background-color: rgba(59,108,212,65%);\n"
"    font-weight: bold;\n"
"}")
        self.deleteall_button.setAutoRepeatDelay(300)
        self.deleteall_button.setObjectName("deleteall_button")
        self.datatable = QtWidgets.QTableWidget(self.centralwidget)
        self.datatable.setGeometry(QtCore.QRect(40, 120, 1021, 421))
        self.datatable.setStyleSheet("QTableWidget{\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QTableWidget:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.datatable.setColumnCount(5)
        self.datatable.setObjectName("datatable")
        self.datatable.setRowCount(0)
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1100, 650))
        self.background.setMinimumSize(QtCore.QSize(1100, 650))
        self.background.setMaximumSize(QtCore.QSize(1100, 650))
        self.background.setMouseTracking(False)
        self.background.setTabletTracking(False)
        self.background.setFocusPolicy(QtCore.Qt.NoFocus)
        self.background.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.background.setAutoFillBackground(False)
        self.background.setStyleSheet("")
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("img/background.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.background_fillter = QtWidgets.QLabel(self.centralwidget)
        self.background_fillter.setGeometry(QtCore.QRect(0, 0, 1100, 650))
        self.background_fillter.setMinimumSize(QtCore.QSize(1100, 650))
        self.background_fillter.setMaximumSize(QtCore.QSize(1100, 650))
        self.background_fillter.setMouseTracking(False)
        self.background_fillter.setTabletTracking(False)
        self.background_fillter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.background_fillter.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.background_fillter.setAutoFillBackground(False)
        self.background_fillter.setStyleSheet("QLabel{\n"
"    background: rgba(34,65,134,60%);\n"
"}")
        self.background_fillter.setText("")
        self.background_fillter.setObjectName("background_fillter")
        self.logout_button = QtWidgets.QPushButton(self.centralwidget)
        self.logout_button.setGeometry(QtCore.QRect(160, 580, 101, 41))
        self.logout_button.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 12pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(74,167,72,95%);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 14pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid #4AA748;\n"
"    background-color: rgba(132,193,65,65%);\n"
"    font-weight: bold;\n"
"}")
        self.logout_button.setAutoRepeatDelay(300)
        self.logout_button.setObjectName("logout_button")
        self.excel_button = QtWidgets.QPushButton(self.centralwidget)
        self.excel_button.setGeometry(QtCore.QRect(810, 580, 111, 41))
        self.excel_button.setStyleSheet("QPushButton{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(34,65,134,90%);\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 14pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid rgb(59,108,212);\n"
"    background-color: rgba(59,108,212,65%);\n"
"    font-weight: bold;\n"
"}")
        self.excel_button.setAutoRepeatDelay(300)
        self.excel_button.setObjectName("excel_button")
        self.search_input = QtWidgets.QLineEdit(self.centralwidget)
        self.search_input.setGeometry(QtCore.QRect(290, 580, 491, 41))
        self.search_input.setStyleSheet("QLineEdit{\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.search_input.setText("")
        self.search_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.search_input.setCursorPosition(0)
        self.search_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.search_input.setObjectName("search_input")
        self.background.raise_()
        self.background_fillter.raise_()
        self.logo.raise_()
        self.tittle_window.raise_()
        self.back_button.raise_()
        self.deleteall_button.raise_()
        self.datatable.raise_()
        self.logout_button.raise_()
        self.excel_button.raise_()
        self.search_input.raise_()
        userinfo_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(userinfo_window)
        QtCore.QMetaObject.connectSlotsByName(userinfo_window)

    def retranslateUi(self, userinfo_window):
        _translate = QtCore.QCoreApplication.translate
        userinfo_window.setWindowTitle(_translate("userinfo_window", "BẢNG DỮ LIỆU CÂU HỎI THÍ SINH"))
        self.tittle_window.setText(_translate("userinfo_window", "BẢNG DỮ LIỆU CÂU HỎI THÍ SINH"))
        self.back_button.setText(_translate("userinfo_window", "Quay lại"))
        self.deleteall_button.setText(_translate("userinfo_window", "Xóa Tất Cả"))
        self.logout_button.setText(_translate("userinfo_window", "Đăng Xuất"))
        self.excel_button.setText(_translate("userinfo_window", "Xuất Excel"))
        self.search_input.setPlaceholderText(_translate("userinfo_window", "   Tìm Kiếm "))
