# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window1_startup.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_startup_window(object):
    def setupUi(self, startup_window):
        startup_window.setObjectName("startup_window")
        startup_window.resize(650, 650)
        startup_window.setMinimumSize(QtCore.QSize(650, 650))
        startup_window.setMaximumSize(QtCore.QSize(650, 650))
        startup_window.setTabletTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        startup_window.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(startup_window)
        self.centralwidget.setObjectName("centralwidget")
        self.admissions_consultancy = QtWidgets.QPushButton(self.centralwidget)
        self.admissions_consultancy.setGeometry(QtCore.QRect(160, 290, 321, 101))
        font = QtGui.QFont()
        font.setFamily("HungHau")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.admissions_consultancy.setFont(font)
        self.admissions_consultancy.setTabletTracking(False)
        self.admissions_consultancy.setAutoFillBackground(False)
        self.admissions_consultancy.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 16pt \"HungHau\";\n"
"    border-radius: 20px;\n"
"    background-color: rgba(74,167,72,95%);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 18pt \"HungHau\";\n"
"    border-radius: 20px;\n"
"    border: 7px solid #4AA748;\n"
"    background-color: rgba(132,193,65,65%);\n"
"    font-weight: bold;\n"
"}")
        self.admissions_consultancy.setObjectName("admissions_consultancy")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(250, 30, 150, 150))
        self.logo.setMinimumSize(QtCore.QSize(150, 150))
        self.logo.setMaximumSize(QtCore.QSize(175, 175))
        self.logo.setStyleSheet("QLabel{\n"
"    image: url(:/newPrefix/logo.png);\n"
"}\n"
"QLabel:hover{\n"
"    image: url(:/newPrefix/logo HHE.png);\n"
"}")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("img/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setWordWrap(False)
        self.logo.setOpenExternalLinks(False)
        self.logo.setObjectName("logo")
        self.admin_form = QtWidgets.QLabel(self.centralwidget)
        self.admin_form.setEnabled(True)
        self.admin_form.setGeometry(QtCore.QRect(160, 400, 321, 171))
        self.admin_form.setMouseTracking(False)
        self.admin_form.setTabletTracking(False)
        self.admin_form.setFocusPolicy(QtCore.Qt.NoFocus)
        self.admin_form.setAcceptDrops(False)
        self.admin_form.setToolTip("")
        self.admin_form.setAccessibleName("")
        self.admin_form.setAutoFillBackground(False)
        self.admin_form.setStyleSheet("QLabel{\n"
"    gridline-color: rgb(32, 47, 255);\n"
"    background-color: rgba(34,65,134,230);\n"
"    border-radius: 20px;\n"
"}")
        self.admin_form.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.admin_form.setText("")
        self.admin_form.setScaledContents(True)
        self.admin_form.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.admin_form.setObjectName("admin_form")
        self.title_formadmin = QtWidgets.QLabel(self.centralwidget)
        self.title_formadmin.setGeometry(QtCore.QRect(210, 410, 251, 31))
        self.title_formadmin.setStyleSheet("font: 75 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;")
        self.title_formadmin.setObjectName("title_formadmin")
        self.loggin_admin = QtWidgets.QPushButton(self.centralwidget)
        self.loggin_admin.setGeometry(QtCore.QRect(370, 510, 91, 41))
        self.loggin_admin.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(74,167,72,95%);\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    border: 3px solid #4AA748;\n"
"    background-color: rgba(132,193,65,65%);\n"
"    font-weight: bold;\n"
"}")
        self.loggin_admin.setAutoRepeatDelay(300)
        self.loggin_admin.setObjectName("loggin_admin")
        self.password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(190, 510, 171, 41))
        self.password_input.setStyleSheet("QLineEdit{\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.password_input.setText("")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 650, 650))
        self.background.setMinimumSize(QtCore.QSize(650, 650))
        self.background.setMaximumSize(QtCore.QSize(650, 650))
        self.background.setMouseTracking(False)
        self.background.setTabletTracking(False)
        self.background.setFocusPolicy(QtCore.Qt.NoFocus)
        self.background.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.background.setAutoFillBackground(False)
        self.background.setStyleSheet("")
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("img/background.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.username_input = QtWidgets.QLineEdit(self.centralwidget)
        self.username_input.setGeometry(QtCore.QRect(190, 450, 271, 41))
        self.username_input.setStyleSheet("QLineEdit{\n"
"    font: 75 10pt \"HungHau\";\n"
"    border-radius: 10px;\n"
"    background-color: rgba(255, 255, 255,80%);\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    font: 75 12pt \"HungHau\";\n"
"    border: 2px solid #92D050;\n"
"    background-color: rgba(255, 255, 255,90%);\n"
"    font-weight: bold;\n"
"}")
        self.username_input.setText("")
        self.username_input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.username_input.setObjectName("username_input")
        self.tittle_app = QtWidgets.QPushButton(self.centralwidget)
        self.tittle_app.setGeometry(QtCore.QRect(110, 180, 431, 101))
        font = QtGui.QFont()
        font.setFamily("HungHau")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tittle_app.setFont(font)
        self.tittle_app.setTabletTracking(False)
        self.tittle_app.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 16pt \"HungHau\";\n"
"    border-radius: 20px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 75 20pt \"HungHau\";\n"
"    border-radius: 20px;\n"
"    font-weight: bold;\n"
"}")
        self.tittle_app.setObjectName("tittle_app")
        self.background_fillter = QtWidgets.QLabel(self.centralwidget)
        self.background_fillter.setGeometry(QtCore.QRect(0, 0, 650, 650))
        self.background_fillter.setMinimumSize(QtCore.QSize(650, 650))
        self.background_fillter.setMaximumSize(QtCore.QSize(650, 650))
        self.background_fillter.setMouseTracking(False)
        self.background_fillter.setTabletTracking(False)
        self.background_fillter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.background_fillter.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.background_fillter.setAutoFillBackground(False)
        self.background_fillter.setStyleSheet("QLabel{\n"
"    background: rgba(34,65,134,60%);\n"
"}")
        self.background_fillter.setText("")
        self.background_fillter.setObjectName("background_fillter")
        self.note = QtWidgets.QLabel(self.centralwidget)
        self.note.setGeometry(QtCore.QRect(150, 570, 341, 31))
        self.note.setStyleSheet("font: 75 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.note.setText("")
        self.note.setAlignment(QtCore.Qt.AlignCenter)
        self.note.setObjectName("note")
        self.background.raise_()
        self.background_fillter.raise_()
        self.admissions_consultancy.raise_()
        self.logo.raise_()
        self.admin_form.raise_()
        self.title_formadmin.raise_()
        self.loggin_admin.raise_()
        self.password_input.raise_()
        self.username_input.raise_()
        self.tittle_app.raise_()
        self.note.raise_()
        startup_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(startup_window)
        QtCore.QMetaObject.connectSlotsByName(startup_window)
        startup_window.setTabOrder(self.admissions_consultancy, self.username_input)
        startup_window.setTabOrder(self.username_input, self.password_input)
        startup_window.setTabOrder(self.password_input, self.loggin_admin)
        startup_window.setTabOrder(self.loggin_admin, self.tittle_app)

    def retranslateUi(self, startup_window):
        _translate = QtCore.QCoreApplication.translate
        startup_window.setWindowTitle(_translate("startup_window", "PHẦN MỀM TƯ VẤN TUYỂN SINH TRƯỜNG ĐẠI HỌC VĂN HIẾN"))
        self.admissions_consultancy.setText(_translate("startup_window", "Tư Vấn Tuyển Sinh"))
        self.title_formadmin.setText(_translate("startup_window", "Đăng nhập quản trị viên"))
        self.loggin_admin.setText(_translate("startup_window", "Đăng Nhập"))
        self.password_input.setPlaceholderText(_translate("startup_window", "Mật Khẩu"))
        self.username_input.setPlaceholderText(_translate("startup_window", "Tài Khoản"))
        self.tittle_app.setText(_translate("startup_window", "Chào mừng bạn đến với trường\n"
"Đại học Văn Hiến"))
